FIX/Refactor: continuous_tests to class
Crypto-TII/claasp pull request #144
Opened 2024-02-19 09:38 UTC by juaninf

2024-02-23 07:22 UTC, peacker requested changes

2024-02-23 07:22 UTC, peacker commented on claasp/cipher_modules/continuous_tests.py
> -def continuous_avalanche_factor(cipher, lambda_value, number_of_samples):
add doctest documentation

2024-02-23 07:22 UTC, peacker commented on claasp/cipher_modules/continuous_tests.py
> +class ContinuousDiffusionAnalysis:
Call it ContinuousDiffusionTests

2024-02-23 07:22 UTC, peacker commented on claasp/cipher.py
> +        self._continuous_tests = ContinuousDiffusionAnalysis(self)
remove references to continuous diffusion from cipher.py

2024-02-23 07:22 UTC, peacker commented on claasp/cipher_modules/continuous_tests.py
> -def continuous_diffusion_tests(cipher,
add documentation from cipher.py

2024-02-27 05:33 UTC, juaninf commented
Declined in favor of Convert continuous diffusion tests to class #158

2024-02-27 05:33 UTC, closed without merging